# 강의노트
### Numpy의 연산과 함수

In [2]:
import numpy as np

In [10]:
# numpy의 곱셈

array = np.random.randint(1, 10, size=4).reshape(2, 2)
print(array)

result_array = array * 10
print(result_array)

[[2 6]
 [7 8]]
[[20 60]
 [70 80]]


In [12]:
# 서로 다른 형태의 배열을 연산할 때 행 우선으로 수행된다.

array1 = np.arange(4).reshape(2, 2) #(2 X 2)
array2 = np.arange(2) #(1 X 2)

array3 = array1 + array2    #[0, 1] 배열이 [[0, 1],
print(array3)               #               [0, 1]] 배열로 변함.

[[0 2]
 [2 4]]


#### 브로드캐스트: 형태가 다른 배열을 연산할 수 있도록 배열의 형태를 동적으로 변환

In [16]:
array1 = np.arange(8).reshape(2, 4) #(2 X 4)
array2 = np.arange(8).reshape(2, 4) #(2 X 4)
array3 = np.concatenate([array1, array2], axis = 0)
array4 = np.arange(4).reshape(4, 1) #(4, 1)

print(array3)
print(array4)
print(array3 + array4)

[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]
[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2  3]
 [ 5  6  7  8]
 [ 2  3  4  5]
 [ 7  8  9 10]]


## 마스킹 연산
### 마스킹: 각원소에 대하여 체크합니다. 원소 값에 조건문을 걸어 True False로 구분함

In [22]:
array1 = np.arange(16).reshape(4, 4)
print(array1)

array2 = array1 < 10    #10보다 작은 값은 True
print(array2)

array1[array2] = 100 # 10보다 작은 값만 100으로 변환
print(array1)

#특정 조건에 맞는 픽셀값을 뽑아오고 정리하여 작업하기 용이하다.

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]


In [25]:
# Numpy의 집계 함수

array1 = np.arange(16).reshape(4, 4)

print("최댓값: ", np.max(array1))
print("최솟값: ", np.min(array1))
print("합계: ", np.sum(array1))
print("평균값: ", np.mean(array1))

최댓값:  15
최솟값:  0
합계:  120
평균값:  7.5


In [30]:
# 각각의 열별로 행별로 합계

print(array1)
print("합계: ", np.sum(array1, axis = 0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
합계:  [24 28 32 36]
